name: macOS

on:
  pull_request:
  push:
  schedule:
    - cron: '00 21 * * *'

jobs:
  general:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
        # 13 - X86_64
        # 14 or latest - Arm64 M1
        version: [13, 14]
        build-tool: [ autotools, cmake ]
        compiler: [ {cpp: clang++, c: clang}, {cpp: g++, c: gcc} ]
        macports-version: [2.10.1]
        exclude:
          - version: 14
            compiler: {cpp: clang++, c: clang}
          # FIXME: temp exclude of failed linking again with cmake + g++ against GRPC dependenncies
          - compiler: {cpp: g++, c: gcc}
            build-tool: cmake
      fail-fast: false

    runs-on: macOS-${{ matrix.version }}
    name: macOS${{ matrix.version }}-${{ matrix.version == '14' && 'arm64' || 'amd64' }}, ${{ matrix.build-tool }}, ${{ matrix.compiler.c }}
    env:
      MACPORTS_ARCHIVE_DIR: $HOME/macports-cache
      MACPORTS_ARCHIVE_FILE: $HOME/macports-cache/macports.tzst

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v4

      - name: Set xcode version
        if: matrix.version == 14
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Unlinking preinstalled Python (workaround)
              # The python@3 brew package has to be installed and linked system-wide (it's a dependency of glib and syslog-ng)
              # The macos-13 GitHub runner has Python preinstalled as a pkg, this prevents linking the python@3
              # brew package, even when linking is forced. `brew "python@3", link: true, force: true`
              # also, brew cannot update the links even these cretated by itself for an earlier python version
        run: |
          find /usr/local/bin/ -lname "*Python.framework*" -delete

      # -------------------------------
      # Cache Homebrew dependencies
      - name: Cache Homebrew dependencies
        uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew-${{ runner.arch }}-${{ hashFiles('contrib/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-${{ runner.arch }}-

      # -------------------------------
      # Install Homebrew dependencies
      - name: Install Homebrew dependencies
        run: |
          if [ "${{ runner.arch }}" = "ARM64" ]; then
            brew update --auto-update
          else
            export HOMEBREW_NO_AUTO_UPDATE=1
            export HOMEBREW_NO_INSTALL_CLEANUP=1
          fi
          brew bundle --force --file=contrib/Brewfile

      # -------------------------------
      # Restore MacPorts self-made archive from cache (if available)
      # NOTE: We cannot use the built-in root restore; we handle extraction manually
      - name: Restore MacPorts archive
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.MACPORTS_ARCHIVE_FILE }}
          key: ${{ runner.os }}-macports-${{ runner.arch }}-${{ matrix.macports-version }}
          restore-keys: |
            ${{ runner.os }}-macports-${{ runner.arch }}-

      # -------------------------------
      # Install MacPorts dependencies
      - name: Install MacPorts dependencies
        run: |
          mkdir -p "$MACPORTS_ARCHIVE_DIR"

          if [ -f "$MACPORTS_ARCHIVE_FILE" ]; then
            echo "Restoring MacPorts from cached archive..."
            sudo tar -C / -xf "$MACPORTS_ARCHIVE_FILE"

            # Ensure macports user and group exist
            if dscl . -read /Users/macports >/dev/null 2>&1 && dscl . -read /Groups/macports >/dev/null 2>&1; then
              echo "macports user and group already exist."
            else
              echo "Creating macports user and group..."
              sudo dscl . -create /Groups/macports
              sudo dscl . -create /Groups/macports PrimaryGroupID 501
              sudo dscl . -create /Users/macports
              sudo dscl . -create /Users/macports UniqueID 503
              sudo dscl . -create /Users/macports PrimaryGroupID 501
              sudo dscl . -create /Users/macports UserShell /usr/bin/false
              sudo dscl . -create /Users/macports NFSHomeDirectory /opt/local/var/macports/home
            fi

            # Fix ownership of extracted files
            echo "Fixing ownership of /opt/local..."
            sudo chown -R macports:macports /opt/local
          else
            echo "Cache missing — installing MacPorts..."
            OS_NAME=$([[ ${{ matrix.version }} -eq 13 ]] && echo "Ventura" || echo "Sonoma")
            MACPORTS_PKG_NAME=MacPorts-${{ matrix.macports-version }}-${{ matrix.version }}-${OS_NAME}.pkg
            MACPORTS_URL=https://github.com/macports/macports-base/releases/download/v${{ matrix.macports-version }}/${MACPORTS_PKG_NAME}

            wget "$MACPORTS_URL" -O "$MACPORTS_ARCHIVE_DIR/$MACPORTS_PKG_NAME"
            sudo installer -pkg "$MACPORTS_ARCHIVE_DIR/$MACPORTS_PKG_NAME" -target /
          fi

          # Ensure MacPorts and ports are up-to-date
          sudo /opt/local/bin/port -v selfupdate
          sudo /opt/local/bin/port upgrade outdated
          sudo /opt/local/bin/port install libesmtp

          # Create/update the archive for caching
          echo "Creating/updating MacPorts archive..."
          sudo tar -C / -cf "$MACPORTS_ARCHIVE_FILE" /opt/local
          sudo chown $USER:staff "$MACPORTS_ARCHIVE_FILE"

      # -------------------------------
      # Upload MacPorts dependencies archive to cache (always)
      - name: Cache MacPorts archive
        if: always()
        uses: actions/cache@v3
        with:
          path: ${{ env.MACPORTS_ARCHIVE_FILE }}
          key: ${{ runner.os }}-macports-${{ runner.arch }}-${{ matrix.macports-version }}
          restore-keys: |
            ${{ runner.os }}-macports-${{ runner.arch }}-

      - name: Set ENV variables
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cpp }}

        run: |
          . .github/workflows/gh-tools.sh

          HOMEBREW_PREFIX="$(brew --prefix)"
          MACPORTS_PREFIX=/opt/local
          SYSLOG_NG_INSTALL_DIR="${HOME}/install/syslog-ng"
          PYTHONUSERBASE="${HOME}/python_packages"
          THREADS="$(sysctl -n hw.physicalcpu)"
          WARNING_FLAGS="-Wno-unused-command-line-argument" # FIXME: -Werror must be re-added
          CFLAGS="-I${HOMEBREW_PREFIX}/include/ -I${MACPORTS_PREFIX}/include ${WARNING_FLAGS}"
          CXXFLAGS="${CFLAGS}"
          # brew has an old autoconf-archive -> ax_cxx_compile_stdcxx.m4 version, which cannot detect
          # correctly the c++14 and c++17 support of clang currently, get the latest one from the git repo
          if [ ${{ matrix.build-tool }} = autotools ] && [ $CC = clang ]; then
            mkdir -p ./m4 || true
            wget -O ./m4/ax_cxx_compile_stdcxx.m4 https://raw.githubusercontent.com/autoconf-archive/autoconf-archive/master/m4/ax_cxx_compile_stdcxx.m4
          fi
          LDFLAGS="-L${HOMEBREW_PREFIX}/lib -L${MACPORTS_PREFIX}/lib"
          CONFIGURE_FLAGS="
            `[ $CC = clang ] && echo '--enable-force-gnu99' || true`
            --enable-extra-warnings
            --enable-debug
            --prefix=${SYSLOG_NG_INSTALL_DIR}
            --enable-tests
            --enable-all-modules
            --with-python=3
            --with-ivykis=internal
            --with-systemd-journal=no
            --disable-java
            --disable-java-modules
          "
          CMAKE_CONFIGURE_FLAGS="
            `[ $CC = clang ] && echo '-DENABLE_FORCE_GNU99=ON' || true`
            -DENABLE_EXTRA_WARNINGS=ON
            -DSUMMARY_LEVEL=1
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_INSTALL_PREFIX=${SYSLOG_NG_INSTALL_DIR}
            -DBUILD_TESTING=ON
            -DPYTHON_VERSION=3
            -DIVYKIS_SOURCE=internal
            -DENABLE_JOURNALD=OFF
            -DENABLE_JAVA=OFF
            -DENABLE_JAVA_MODULES=OFF
          "
          PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/openssl@3/lib/pkgconfig:${HOMEBREW_PREFIX}/opt/net-snmp/lib/pkgconfig:${HOMEBREW_PREFIX}/lib/pkgconfig:${MACPORTS_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
          PATH="${HOMEBREW_PREFIX}/opt/bison/bin:${HOMEBREW_PREFIX}/opt/libnet/bin:${HOMEBREW_PREFIX}/opt/net-snmp/bin:${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PYTHONUSERBASE}/bin:${MACPORTS_PREFIX}/bin:${MACPORTS_PREFIX}/sbin:${PATH}"

          gh_export HOMEBREW_PREFIX MACPORTS_PREFIX SYSLOG_NG_INSTALL_DIR PYTHONUSERBASE CC CXX PKG_CONFIG_PATH THREADS CONFIGURE_FLAGS CFLAGS CXXFLAGS LDFLAGS CMAKE_CONFIGURE_FLAGS PATH
          gh_path "${PATH}"

          env | sort
          #cat "${GITHUB_ENV}" | sort

      - name: Set gcc and g++ symlinks
        run: |
          if [ $CC = gcc ]; then
            ln -s "${HOMEBREW_PREFIX}/bin/gcc-14" "${HOMEBREW_PREFIX}/bin/gcc"
            ln -s "${HOMEBREW_PREFIX}/bin/g++-14" "${HOMEBREW_PREFIX}/bin/g++"
          fi

          echo "ARCH: " $(arch)
          echo "xcode:" $(xcode-select -p)
          echo "gcc:" $(which gcc; gcc --version)
          echo "g++:" $(which g++; g++ --version)
          echo "clang:" $(which clang; clang --version)

      - name: autogen.sh
        if: matrix.build-tool == 'autotools'
        run: |
          ./autogen.sh

      - name: configure
        if: matrix.build-tool == 'autotools'
        run: |
          ./configure ${CONFIGURE_FLAGS}

      - name: cmake configure
        if: matrix.build-tool == 'cmake'
        run: |
          cmake --install-prefix "${SYSLOG_NG_INSTALL_DIR}" -B build . ${CMAKE_CONFIGURE_FLAGS}

      - name: cmake install
        if: matrix.build-tool == 'cmake'
        run: |
          cmake --build ./build -j ${THREADS} --target install
          "${SYSLOG_NG_INSTALL_DIR}/sbin/syslog-ng" -V

      - name: cmake check
        # FIXME: Some of our checks still do not run correctly on silicon yet (and probably never will)
        if: matrix.build-tool == 'cmake' && matrix.version != 14
        run: |
          cmake --build ./build -j ${THREADS} --target check

      - name: make install
        if: matrix.build-tool == 'autotools'
        run: |
          set -e

          make --keep-going install -j ${THREADS} || \
            { \
              S=$?; \
              make V=1; \
              return $S; \
            }
          "${SYSLOG_NG_INSTALL_DIR}/sbin/syslog-ng" -V

      - name: make check
        # FIXME: Some of our checks still do not run correctly on silicon yet (and probably never will)
        if: matrix.build-tool == 'autotools' && matrix.version != 14
        run: |
          set -e

          make --keep-going check -j ${THREADS} || \
            { \
              S=$?; \
              echo "Output of first test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              make V=1 check; \
              echo "Output of second test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              return $S; \
            }
