name: Master Branch PR check

on:
  pull_request:
    branches:
      - master

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != develop ]];
          then
            echo "Error: Pull request to 'master' must come from 'develop'"
            exit 1
          fi
