name: Trigger Publish Docker image


on:
  workflow_call:
  workflow_dispatch:
    inputs:
      pkg-type:
        description: Package type
        required: true
        type: choice
        options:
          - nightly
          - stable

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag
        run: |
          if [[ "${{ github.ref }}" != refs/tags/syslog-ng-* ]] && [[ "${{ inputs.pkg-type }}" != "nightly" ]]; then
            echo "Please start the workflow on a 'syslog-ng-*' tag"
            false
          fi

  publish-docker-image:
    needs: pre-check
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      pkg-type: ${{ inputs.pkg-type }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
