name: Trigger Publish Docker image


on:
  workflow_call:
  workflow_dispatch:
    inputs:
      pkg-type:
        description: Package type
        required: true
        type: choice
        options:
          - nightly
          - stable
      pkg-version:
        description: Version (<MAJOR>.<MINOR>.<PATCH>)
        required: false
        type: string
      pkg-push:
        description: Push to docker
        required: false
        type: boolean
        default: false

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate tag
        run: |
          if [[ "${{ github.ref }}" != refs/tags/syslog-ng-* ]] && [[ "${{ inputs.pkg-type }}" != "nightly" ]] && [[ "${{ inputs.pkg-version }}" == "" ]]; then
            echo "Please start the workflow on a 'syslog-ng-*' tag or provide an exact version number"
            false
          fi

  publish-docker-image:
    needs: pre-check
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      pkg-type: ${{ inputs.pkg-type }}
      pkg-version: ${{ inputs.pkg-version }}
      pkg-push: ${{ inputs.pkg-push }}
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
